### ISSUE TITLE
Export-vROResourceElement not UTF8 friendly.

### ISSUE THREAD

**Issue by cjchacon** [jakkulabs/PowervRO#12]
Steps to reproduce
------------------
Download any plain text resource file with a "ñ" or "ó".

Expected behavior
-----------------
Downloaded plain text files should use UTF8 character encoding.

Actual behavior
---------------
Downloaded plain text files with international characters are not displayed as expected.
![imagen](https://user-images.githubusercontent.com/2378321/38736489-80d3856c-3f2c-11e8-90b4-94eb79840834.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> $vROConnection
Server             : https://pcloudportal:443
Username           : x
EncodedPassword    : x
Version            : 7.3.0.5481809
APIVersion         : 5.5.2
SignedCertificates : True
SslProtocol        : Tls12
```

**Comment by jonathanmedd** [comment]
Thanks for this. My initial thought is that we will resolve it either by changing the default encoding output and / or offering an encoding parameter to the function.

As you may know the default encodings in PowerShell have changed between Windows PowerShell 5.1 and PowerShell Core 6 (https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0020-DefaultFileEncoding.md) , so we will need to come up with a consistent approach for both versions.
