### ISSUE TITLE
Object returned by Invoke-vROWorkflow can not be pipelined to other cmdlets

### ISSUE THREAD

**Issue by voroniys** [jakkulabs/PowervRO#15]
Steps to reproduce
------------------
Invoke-vROWorkflow -Id $vro_wf_id | Get-vROWorkflowExecutionState

Expected behavior
-----------------
Should get an execution state

Actual behavior
---------------
Get-vROWorkflowExecutionState failed with error. 

Cause and solution
----------------
The issue cause by the wrong data in Execution property. It is 
a - array
b - full URL

The solution is in pull request #14

**Comment by jonathanmedd** [comment]
@voroniys Thanks a lot for this! Have merged your PR.
