### ISSUE TITLE
Get-vrOWorkflowExecution

### ISSUE THREAD

**Issue by ulrik-n** [jakkulabs/PowervRO#4]
Get-vROWorkflowExecution has a fixed reference to the vRO port 8182.
`$ExecutionURI = ("$($ItemHref)executions/" -split "8281")[1]`

To make the function dynamic you should get the port from the current vRO connection, e.g.
`$vROConnectionPort = $Global:vROConnection.Server.Split(':')[-1]`
`$ExecutionURI = ("$($ItemHref)executions/" -split $vROConnectionPort)[1]`

**Comment by chelnak** [comment]
Good spot! We have done this elsewhere as some functions failed against
embedded instances.

Feel free to submit a PR with a fix and it will make its way in to the next
release!

**Comment by jonathanmedd** [comment]
@chelnak You already fixed this, it's in the Develop branch:

https://github.com/jakkulabs/PowervRO/commit/236d396cf93b3364c04b1ae026e5dfe8f71ca6fc#diff-736dc5a23e612de26a6bcb857e79f54f

**Comment by chelnak** [comment]
Haha. Excellent.
