### ISSUE TITLE
Typo: $Global:vRAConnection

### ISSUE THREAD

**Issue by Aly-ona** [jakkulabs/PowervRO#9]
https://github.com/jakkulabs/PowervRO/blob/0c0bffe0d4fcf2c9d6fca9232a8a8e0cc7ba7e54/src/Functions/Public/Invoke-vRORestMethod.ps1#L130

Hello,

Looks like a typo. Should it be $Global:vROConnection ?

**Comment by chelnak** [comment]
Good spot. We will get a fix out for this asap.

**Comment by jonathanmedd** [comment]
@Aly-ona Thanks for that. The fix will be in the 2.0.1 release
